### ISSUE TITLE
'index.js' contains a valid Azure application insights key.

### ISSUE THREAD

**Issue by HalidCisse** [microsoft/sarif-pattern-matcher#459]
I'm getting this alert in a react front-end app, using the [official client](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript-react-plugin).

![image](https://user-images.githubusercontent.com/6313791/118840804-a4ea1280-b8bf-11eb-9a08-5a8bf466e00c.png)

Azure application insights instrumentation keys are not secrets and can be shipped in client apps.

**Comment by eddynaka** [comment]
Hi,

you can ship in a front-end, but some attacker could get your key and add so much data that you wouldn't see yours, for example.

With that in mind, we are suggesting protecting it.

Right now, the AppInsightsKey has a warning level, which is not required to fix (since there are cases, for example, front-end pages, which might get more complicated). But we recommend using KV to store it.

This can give you an idea of how to fix it: https://devblogs.microsoft.com/premier-developer/alternative-way-to-protect-your-application-insights-instrumentation-key-in-javascript/

**Comment by eddynaka** [comment]
Hi Halid, after some review, we dropped the level from Error -> Warning.
With that, it won't flag during PRs.

I'm closing the PR for now.

Feel free to re-open.
Thank you!
